version: '3.9'

services:
  reactapp:
    build:
      context: reactapp.client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - keycloak
    networks:
      - app-network

  backend:
    build:  
      context: ReactApp.Server
      dockerfile: Dockerfile
    ports:
      - "5080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=80
    depends_on:
      - keycloak
    networks:
      - app-network
      
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: start-dev
    environment:
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        #KC_HOSTNAME: http://localhost:8080
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    
    ports:
      - "5432:5432"

    volumes:
      - postgres_data_keycloack:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data_keycloack:
    
networks:
  app-network:
    driver: bridge